"""add_temporal_and_extended_schema

Revision ID: 125ebba5f7c3
Revises: 67a879aff557
Create Date: 2025-11-25 13:54:27.667037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '125ebba5f7c3'
down_revision: Union[str, Sequence[str], None] = '67a879aff557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_merge_candidates',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('primary_entity_id', sa.Uuid(), nullable=False),
    sa.Column('duplicate_entity_id', sa.Uuid(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('merge_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detected_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['primary_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_merge_candidates_duplicate_entity_id'), 'entity_merge_candidates', ['duplicate_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_merge_candidates_primary_entity_id'), 'entity_merge_candidates', ['primary_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_merge_candidates_status'), 'entity_merge_candidates', ['status'], unique=False)
    op.create_index(op.f('ix_entity_merge_candidates_vault_id'), 'entity_merge_candidates', ['vault_id'], unique=False)
    op.create_table('era_tags',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_era_tags_name'), 'era_tags', ['name'], unique=False)
    op.create_index(op.f('ix_era_tags_vault_id'), 'era_tags', ['vault_id'], unique=False)
    op.create_table('fact_conflicts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('fact_a_id', sa.Uuid(), nullable=False),
    sa.Column('fact_b_id', sa.Uuid(), nullable=False),
    sa.Column('conflict_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolution_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('canonical_fact_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('detected_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detected_at_scene_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_fact_id'], ['facts.id'], ),
    sa.ForeignKeyConstraint(['detected_at_scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['fact_a_id'], ['facts.id'], ),
    sa.ForeignKeyConstraint(['fact_b_id'], ['facts.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_conflicts_fact_a_id'), 'fact_conflicts', ['fact_a_id'], unique=False)
    op.create_index(op.f('ix_fact_conflicts_fact_b_id'), 'fact_conflicts', ['fact_b_id'], unique=False)
    op.create_index(op.f('ix_fact_conflicts_status'), 'fact_conflicts', ['status'], unique=False)
    op.create_index(op.f('ix_fact_conflicts_vault_id'), 'fact_conflicts', ['vault_id'], unique=False)
    op.create_table('lore_entries',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related_entity_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_scene_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('times_referenced', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lore_entries_category'), 'lore_entries', ['category'], unique=False)
    op.create_index(op.f('ix_lore_entries_title'), 'lore_entries', ['title'], unique=False)
    op.create_index(op.f('ix_lore_entries_vault_id'), 'lore_entries', ['vault_id'], unique=False)
    op.create_table('narrators',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('narrator_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('biases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrators_name'), 'narrators', ['name'], unique=False)
    op.create_index(op.f('ix_narrators_vault_id'), 'narrators', ['vault_id'], unique=False)
    op.create_table('ordering_constraints',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('source_scene_id', sa.Uuid(), nullable=False),
    sa.Column('target_scene_id', sa.Uuid(), nullable=False),
    sa.Column('constraint_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['source_scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['target_scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordering_constraints_source_scene_id'), 'ordering_constraints', ['source_scene_id'], unique=False)
    op.create_index(op.f('ix_ordering_constraints_target_scene_id'), 'ordering_constraints', ['target_scene_id'], unique=False)
    op.create_index(op.f('ix_ordering_constraints_vault_id'), 'ordering_constraints', ['vault_id'], unique=False)
    op.create_table('pov_boundaries',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('known_fact_id', sa.Uuid(), nullable=False),
    sa.Column('learned_at_scene_id', sa.Uuid(), nullable=True),
    sa.Column('learned_at_timestamp', sa.DateTime(), nullable=True),
    sa.Column('certainty', sa.Float(), nullable=False),
    sa.Column('is_false_belief', sa.Boolean(), nullable=False),
    sa.Column('forgotten_at_scene_id', sa.Uuid(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['forgotten_at_scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['known_fact_id'], ['facts.id'], ),
    sa.ForeignKeyConstraint(['learned_at_scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pov_boundaries_character_id'), 'pov_boundaries', ['character_id'], unique=False)
    op.create_index(op.f('ix_pov_boundaries_known_fact_id'), 'pov_boundaries', ['known_fact_id'], unique=False)
    op.create_index(op.f('ix_pov_boundaries_vault_id'), 'pov_boundaries', ['vault_id'], unique=False)
    op.create_table('prophecy_visions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prophet_id', sa.Uuid(), nullable=True),
    sa.Column('prophecy_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uttered_at_scene_id', sa.Uuid(), nullable=True),
    sa.Column('discovered_at_scene_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fulfilled_at_scene_id', sa.Uuid(), nullable=True),
    sa.Column('fulfillment_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('possible_interpretations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['discovered_at_scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['fulfilled_at_scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['prophet_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['uttered_at_scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prophecy_visions_status'), 'prophecy_visions', ['status'], unique=False)
    op.create_index(op.f('ix_prophecy_visions_vault_id'), 'prophecy_visions', ['vault_id'], unique=False)
    op.create_table('world_dates',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('calendar_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conversion_formula', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_dates_name'), 'world_dates', ['name'], unique=False)
    op.create_index(op.f('ix_world_dates_vault_id'), 'world_dates', ['vault_id'], unique=False)
    op.create_table('scene_narrators',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('narrator_id', sa.Uuid(), nullable=False),
    sa.Column('reliability_override', sa.Float(), nullable=True),
    sa.Column('narrative_distance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['narrator_id'], ['narrators.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_narrators_narrator_id'), 'scene_narrators', ['narrator_id'], unique=False)
    op.create_index(op.f('ix_scene_narrators_scene_id'), 'scene_narrators', ['scene_id'], unique=False)
    op.create_index(op.f('ix_scene_narrators_vault_id'), 'scene_narrators', ['vault_id'], unique=False)
    op.create_table('time_frames',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('real_world_date', sa.DateTime(), nullable=True),
    sa.Column('real_world_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('world_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('world_date_sort_key', sa.Integer(), nullable=True),
    sa.Column('era_id', sa.Uuid(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('days_since_story_start', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['era_id'], ['era_tags.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_frames_scene_id'), 'time_frames', ['scene_id'], unique=True)
    op.create_index(op.f('ix_time_frames_vault_id'), 'time_frames', ['vault_id'], unique=False)
    op.create_table('temporal_anchors',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scene_id', sa.Uuid(), nullable=True),
    sa.Column('time_frame_id', sa.Uuid(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('times_referenced', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['time_frame_id'], ['time_frames.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporal_anchors_name'), 'temporal_anchors', ['name'], unique=False)
    op.create_index(op.f('ix_temporal_anchors_vault_id'), 'temporal_anchors', ['vault_id'], unique=False)

    # Create enum types before using them
    conflictrole_enum = sa.Enum('PROTAGONIST', 'ANTAGONIST', 'INSTIGATOR', 'BYSTANDER', name='conflictrole')
    conflictrole_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('conflict_participants', 'role',
               existing_type=sa.VARCHAR(),
               type_=conflictrole_enum,
               existing_nullable=False,
               postgresql_using='role::conflictrole')
    op.drop_column('conflict_participants', 'created_at')
    op.drop_column('conflict_participants', 'updated_at')

    # Create enum types for conflicts table
    conflicttype_enum = sa.Enum('PERSON_VS_PERSON', 'PERSON_VS_SELF', 'PERSON_VS_NATURE', 'PERSON_VS_SOCIETY', 'PERSON_VS_SUPERNATURAL', 'PERSON_VS_TECHNOLOGY', name='conflicttype')
    conflicttype_enum.create(op.get_bind(), checkfirst=True)
    conflictstatus_enum = sa.Enum('SETUP', 'INCITING_INCIDENT', 'RISING_ACTION', 'CLIMAX', 'FALLING_ACTION', 'RESOLUTION', name='conflictstatus')
    conflictstatus_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('conflicts', 'conflict_type',
               existing_type=sa.VARCHAR(),
               type_=conflicttype_enum,
               existing_nullable=False,
               postgresql_using='conflict_type::conflicttype')
    op.alter_column('conflicts', 'status',
               existing_type=sa.VARCHAR(),
               type_=conflictstatus_enum,
               existing_nullable=False,
               postgresql_using='status::conflictstatus')
    op.drop_index(op.f('documents_embedding_hnsw_idx'), table_name='documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index('ix_documents_embedding', 'documents', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('entities_embedding_hnsw_idx'), table_name='entities', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index('ix_entities_embedding', 'entities', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_events_embedding', 'events', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('facts_embedding_hnsw_idx'), table_name='facts', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index('ix_facts_embedding', 'facts', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.add_column('limit_breaches', sa.Column('vault_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_limit_breaches_vault_id'), 'limit_breaches', ['vault_id'], unique=False)
    op.create_index('ix_scenes_embedding', 'scenes', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.add_column('sprints', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('sprints', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('sprints', sa.Column('vault_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_sprints_vault_id'), 'sprints', ['vault_id'], unique=False)
    op.add_column('style_reports', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('style_reports', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('style_reports', sa.Column('vault_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_style_reports_vault_id'), 'style_reports', ['vault_id'], unique=False)
    op.add_column('symbols', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('symbols', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('symbols', sa.Column('vault_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_symbols_vault_id'), 'symbols', ['vault_id'], unique=False)
    op.add_column('system_rules', sa.Column('vault_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_system_rules_vault_id'), 'system_rules', ['vault_id'], unique=False)
    op.add_column('themes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('themes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('themes', sa.Column('vault_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_themes_vault_id'), 'themes', ['vault_id'], unique=False)
    op.add_column('timeline_events', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('timeline_events', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('timeline_events', sa.Column('vault_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_timeline_events_vault_id'), 'timeline_events', ['vault_id'], unique=False)
    op.add_column('transformation_moments', sa.Column('vault_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_transformation_moments_vault_id'), 'transformation_moments', ['vault_id'], unique=False)
    op.add_column('travel_routes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('travel_routes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('travel_routes', sa.Column('vault_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_travel_routes_vault_id'), 'travel_routes', ['vault_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_routes_vault_id'), table_name='travel_routes')
    op.drop_column('travel_routes', 'vault_id')
    op.drop_column('travel_routes', 'updated_at')
    op.drop_column('travel_routes', 'created_at')
    op.drop_index(op.f('ix_transformation_moments_vault_id'), table_name='transformation_moments')
    op.drop_column('transformation_moments', 'vault_id')
    op.drop_index(op.f('ix_timeline_events_vault_id'), table_name='timeline_events')
    op.drop_column('timeline_events', 'vault_id')
    op.drop_column('timeline_events', 'updated_at')
    op.drop_column('timeline_events', 'created_at')
    op.drop_index(op.f('ix_themes_vault_id'), table_name='themes')
    op.drop_column('themes', 'vault_id')
    op.drop_column('themes', 'updated_at')
    op.drop_column('themes', 'created_at')
    op.drop_index(op.f('ix_system_rules_vault_id'), table_name='system_rules')
    op.drop_column('system_rules', 'vault_id')
    op.drop_index(op.f('ix_symbols_vault_id'), table_name='symbols')
    op.drop_column('symbols', 'vault_id')
    op.drop_column('symbols', 'updated_at')
    op.drop_column('symbols', 'created_at')
    op.drop_index(op.f('ix_style_reports_vault_id'), table_name='style_reports')
    op.drop_column('style_reports', 'vault_id')
    op.drop_column('style_reports', 'updated_at')
    op.drop_column('style_reports', 'created_at')
    op.drop_index(op.f('ix_sprints_vault_id'), table_name='sprints')
    op.drop_column('sprints', 'vault_id')
    op.drop_column('sprints', 'updated_at')
    op.drop_column('sprints', 'created_at')
    op.drop_index('ix_scenes_embedding', table_name='scenes', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_limit_breaches_vault_id'), table_name='limit_breaches')
    op.drop_column('limit_breaches', 'vault_id')
    op.drop_index('ix_facts_embedding', table_name='facts', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('facts_embedding_hnsw_idx'), 'facts', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index('ix_events_embedding', table_name='events', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_entities_embedding', table_name='entities', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('entities_embedding_hnsw_idx'), 'entities', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index('ix_documents_embedding', table_name='documents', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('documents_embedding_hnsw_idx'), 'documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('conflicts', 'status',
               existing_type=sa.Enum('SETUP', 'INCITING_INCIDENT', 'RISING_ACTION', 'CLIMAX', 'FALLING_ACTION', 'RESOLUTION', name='conflictstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('conflicts', 'conflict_type',
               existing_type=sa.Enum('PERSON_VS_PERSON', 'PERSON_VS_SELF', 'PERSON_VS_NATURE', 'PERSON_VS_SOCIETY', 'PERSON_VS_SUPERNATURAL', 'PERSON_VS_TECHNOLOGY', name='conflicttype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('conflict_participants', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('conflict_participants', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('conflict_participants', 'role',
               existing_type=sa.Enum('PROTAGONIST', 'ANTAGONIST', 'INSTIGATOR', 'BYSTANDER', name='conflictrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_temporal_anchors_vault_id'), table_name='temporal_anchors')
    op.drop_index(op.f('ix_temporal_anchors_name'), table_name='temporal_anchors')
    op.drop_table('temporal_anchors')
    op.drop_index(op.f('ix_time_frames_vault_id'), table_name='time_frames')
    op.drop_index(op.f('ix_time_frames_scene_id'), table_name='time_frames')
    op.drop_table('time_frames')
    op.drop_index(op.f('ix_scene_narrators_vault_id'), table_name='scene_narrators')
    op.drop_index(op.f('ix_scene_narrators_scene_id'), table_name='scene_narrators')
    op.drop_index(op.f('ix_scene_narrators_narrator_id'), table_name='scene_narrators')
    op.drop_table('scene_narrators')
    op.drop_index(op.f('ix_world_dates_vault_id'), table_name='world_dates')
    op.drop_index(op.f('ix_world_dates_name'), table_name='world_dates')
    op.drop_table('world_dates')
    op.drop_index(op.f('ix_prophecy_visions_vault_id'), table_name='prophecy_visions')
    op.drop_index(op.f('ix_prophecy_visions_status'), table_name='prophecy_visions')
    op.drop_table('prophecy_visions')
    op.drop_index(op.f('ix_pov_boundaries_vault_id'), table_name='pov_boundaries')
    op.drop_index(op.f('ix_pov_boundaries_known_fact_id'), table_name='pov_boundaries')
    op.drop_index(op.f('ix_pov_boundaries_character_id'), table_name='pov_boundaries')
    op.drop_table('pov_boundaries')
    op.drop_index(op.f('ix_ordering_constraints_vault_id'), table_name='ordering_constraints')
    op.drop_index(op.f('ix_ordering_constraints_target_scene_id'), table_name='ordering_constraints')
    op.drop_index(op.f('ix_ordering_constraints_source_scene_id'), table_name='ordering_constraints')
    op.drop_table('ordering_constraints')
    op.drop_index(op.f('ix_narrators_vault_id'), table_name='narrators')
    op.drop_index(op.f('ix_narrators_name'), table_name='narrators')
    op.drop_table('narrators')
    op.drop_index(op.f('ix_lore_entries_vault_id'), table_name='lore_entries')
    op.drop_index(op.f('ix_lore_entries_title'), table_name='lore_entries')
    op.drop_index(op.f('ix_lore_entries_category'), table_name='lore_entries')
    op.drop_table('lore_entries')
    op.drop_index(op.f('ix_fact_conflicts_vault_id'), table_name='fact_conflicts')
    op.drop_index(op.f('ix_fact_conflicts_status'), table_name='fact_conflicts')
    op.drop_index(op.f('ix_fact_conflicts_fact_b_id'), table_name='fact_conflicts')
    op.drop_index(op.f('ix_fact_conflicts_fact_a_id'), table_name='fact_conflicts')
    op.drop_table('fact_conflicts')
    op.drop_index(op.f('ix_era_tags_vault_id'), table_name='era_tags')
    op.drop_index(op.f('ix_era_tags_name'), table_name='era_tags')
    op.drop_table('era_tags')
    op.drop_index(op.f('ix_entity_merge_candidates_vault_id'), table_name='entity_merge_candidates')
    op.drop_index(op.f('ix_entity_merge_candidates_status'), table_name='entity_merge_candidates')
    op.drop_index(op.f('ix_entity_merge_candidates_primary_entity_id'), table_name='entity_merge_candidates')
    op.drop_index(op.f('ix_entity_merge_candidates_duplicate_entity_id'), table_name='entity_merge_candidates')
    op.drop_table('entity_merge_candidates')
    # ### end Alembic commands ###
