"""add hybrid architecture foundation (User, Vault, enums, vault_id isolation)

Revision ID: 67a879aff557
Revises: c3d4e5f6g7h8
Create Date: 2025-11-24 22:25:38.511675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67a879aff557'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchors',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ON_TRACK', 'AT_RISK', 'COMPLETED', name='anchorstatus'), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('chapters_remaining', sa.Integer(), nullable=True),
    sa.Column('on_track_score', sa.Float(), nullable=False),
    sa.Column('canon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anchors_status'), 'anchors', ['status'], unique=False)
    op.create_index(op.f('ix_anchors_vault_id'), 'anchors', ['vault_id'], unique=False)
    op.create_table('chapters',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('OUTLINE', 'DRAFT', 'REVISED', 'FINAL', name='draftstatus'), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_chapter_number'), 'chapters', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapters_vault_id'), 'chapters', ['vault_id'], unique=False)
    op.create_table('conflicts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conflict_type', sa.Enum('PERSON_VS_PERSON', 'PERSON_VS_SELF', 'PERSON_VS_NATURE', 'PERSON_VS_SOCIETY', 'PERSON_VS_SUPERNATURAL', 'PERSON_VS_TECHNOLOGY', name='conflicttype'), nullable=False),
    sa.Column('status', sa.Enum('SETUP', 'INCITING_INCIDENT', 'RISING_ACTION', 'CLIMAX', 'FALLING_ACTION', 'RESOLUTION', name='conflictstatus'), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('stakes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('canon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_conflict_type'), 'conflicts', ['conflict_type'], unique=False)
    op.create_index('ix_conflicts_embedding', 'conflicts', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_conflicts_status'), 'conflicts', ['status'], unique=False)
    op.create_index(op.f('ix_conflicts_vault_id'), 'conflicts', ['vault_id'], unique=False)
    op.create_table('conversations',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_vault_id'), 'conversations', ['vault_id'], unique=False)
    op.create_table('entities',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('CHARACTER', 'LOCATION', 'FACTION', 'ITEM', 'ABILITY', 'MAGIC_SYSTEM', 'TECH_SYSTEM', 'EVENT', 'PLOT_THREAD', 'NOTE', 'SCENE', name='entitytype'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ALIVE', 'DEAD', 'MISSING', 'UNKNOWN', 'UNDEAD', 'DORMANT', 'ASCENDED', 'IMPRISONED', 'EXILED', name='entitystatus'), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('species', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_date', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('death_date', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_embedding', 'entities', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_index(op.f('ix_entities_status'), 'entities', ['status'], unique=False)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_index(op.f('ix_entities_vault_id'), 'entities', ['vault_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('story_time', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative_time', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('causes_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_embedding', 'events', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_events_sequence_order'), 'events', ['sequence_order'], unique=False)
    op.create_index(op.f('ix_events_vault_id'), 'events', ['vault_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vault_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_event_type'), 'interactions', ['event_type'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_interactions_vault_id'), 'interactions', ['vault_id'], unique=False)
    op.create_table('sources',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('user_rating', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='userrating'), nullable=True),
    sa.Column('times_cited_by_user', sa.Integer(), nullable=False),
    sa.Column('times_cited_by_archivist', sa.Integer(), nullable=False),
    sa.Column('times_rejected_by_user', sa.Integer(), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('genre_focus', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprints',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('goal_word_count', sa.Integer(), nullable=False),
    sa.Column('current_word_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_vault_id'), 'sprints', ['vault_id'], unique=False)
    op.create_table('themes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_vault_id'), 'themes', ['vault_id'], unique=False)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'MINI', 'PRO', 'BYOK', name='subscriptiontier'), nullable=False),
    sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('character_arcs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('arc_type', sa.Enum('POSITIVE', 'NEGATIVE', 'FLAT', 'CORRUPTION', 'REDEMPTION', 'DISILLUSIONMENT', 'COMING_OF_AGE', name='arctype'), nullable=False),
    sa.Column('arc_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starting_state_id', sa.Uuid(), nullable=False),
    sa.Column('ending_state_id', sa.Uuid(), nullable=True),
    sa.Column('current_state_id', sa.Uuid(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_arcs_character_id'), 'character_arcs', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_arcs_vault_id'), 'character_arcs', ['vault_id'], unique=False)
    op.create_table('character_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('story_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('psych_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_states_character_id'), 'character_states', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_states_sequence_order'), 'character_states', ['sequence_order'], unique=False)
    op.create_table('conflict_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conflict_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('PROTAGONIST', 'ANTAGONIST', 'INSTIGATOR', 'BYSTANDER', name='conflictrole'), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id', 'conflict_id', 'entity_id')
    )
    op.create_table('documents',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_embedding', 'documents', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_documents_vault_id'), 'documents', ['vault_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('fact_type', sa.Enum('TRAIT', 'ABILITY', 'RELATIONSHIP', 'EVENT', 'FEAR', 'DESIRE', 'TRAUMA', 'MOTIVATION', name='facttype'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('canon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facts_embedding', 'facts', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_facts_entity_id'), 'facts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_facts_fact_type'), 'facts', ['fact_type'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('relationships',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('from_entity_id', sa.Uuid(), nullable=False),
    sa.Column('to_entity_id', sa.Uuid(), nullable=False),
    sa.Column('rel_type', sa.Enum('FRIEND', 'ENEMY', 'ALLY', 'RIVAL', 'FAMILY', 'PARENT', 'CHILD', 'SIBLING', 'SPOUSE', 'MENTOR', 'MENTEE', 'EMPLOYED_BY', 'LEADS', 'MEMBER_OF', 'ROMANTIC_INTEREST', 'EX_PARTNER', 'BETRAYED', 'OWES_DEBT_TO', 'SAVED_BY', 'KILLED', 'CREATED_BY', 'WORSHIPS', 'BLESSED_BY', 'CURSED_BY', 'LOCATED_IN', 'CONNECTED_TO', 'OWNS', 'HAS_ABILITY', 'REQUIRES', 'CAUSES', 'RELATED_TO', 'REFERENCES', 'APPEARS_IN', name='relationtype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relationship_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effective_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effective_until', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_from_entity_id'), 'relationships', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_rel_type'), 'relationships', ['rel_type'], unique=False)
    op.create_index(op.f('ix_relationships_to_entity_id'), 'relationships', ['to_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_vault_id'), 'relationships', ['vault_id'], unique=False)
    op.create_table('scenes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=True),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('tension_level', sa.Integer(), nullable=False),
    sa.Column('dominant_emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pacing', sa.Enum('SLOW', 'MEDIUM', 'FAST', name='pacingtype'), nullable=False),
    sa.Column('pov_character_id', sa.Uuid(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenes_embedding', 'scenes', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_scenes_scene_number'), 'scenes', ['scene_number'], unique=False)
    op.create_index(op.f('ix_scenes_vault_id'), 'scenes', ['vault_id'], unique=False)
    op.create_table('symbols',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meaning', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_vault_id'), 'symbols', ['vault_id'], unique=False)
    op.create_table('system_rules',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_entity_id', sa.Uuid(), nullable=False),
    sa.Column('consequences', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_rules_vault_id'), 'system_rules', ['vault_id'], unique=False)
    op.create_table('travel_routes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('origin_id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('travel_time_days', sa.Float(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_routes_vault_id'), 'travel_routes', ['vault_id'], unique=False)
    op.create_table('vaults',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('connection_type', sa.Enum('LOCAL_OBSIDIAN', 'CLOUD_HOSTED', name='connectiontype'), nullable=False),
    sa.Column('local_system_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('scene_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaults_owner_id'), 'vaults', ['owner_id'], unique=False)
    op.create_table('limit_breaches',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('consequence_manifested', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['system_rules.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_limit_breaches_vault_id'), 'limit_breaches', ['vault_id'], unique=False)
    op.create_table('style_reports',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=False),
    sa.Column('passive_voice_count', sa.Integer(), nullable=False),
    sa.Column('adverb_count', sa.Integer(), nullable=False),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_reports_vault_id'), 'style_reports', ['vault_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('date_str', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('absolute_timestamp', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_vault_id'), 'timeline_events', ['vault_id'], unique=False)
    op.create_table('transformation_moments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_belief', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('new_belief', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformation_moments_character_id'), 'transformation_moments', ['character_id'], unique=False)
    op.create_index(op.f('ix_transformation_moments_vault_id'), 'transformation_moments', ['vault_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transformation_moments_vault_id'), table_name='transformation_moments')
    op.drop_index(op.f('ix_transformation_moments_character_id'), table_name='transformation_moments')
    op.drop_table('transformation_moments')
    op.drop_index(op.f('ix_timeline_events_vault_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_style_reports_vault_id'), table_name='style_reports')
    op.drop_table('style_reports')
    op.drop_index(op.f('ix_limit_breaches_vault_id'), table_name='limit_breaches')
    op.drop_table('limit_breaches')
    op.drop_index(op.f('ix_vaults_owner_id'), table_name='vaults')
    op.drop_table('vaults')
    op.drop_index(op.f('ix_travel_routes_vault_id'), table_name='travel_routes')
    op.drop_table('travel_routes')
    op.drop_index(op.f('ix_system_rules_vault_id'), table_name='system_rules')
    op.drop_table('system_rules')
    op.drop_index(op.f('ix_symbols_vault_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_scenes_vault_id'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_scene_number'), table_name='scenes')
    op.drop_index('ix_scenes_embedding', table_name='scenes', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('scenes')
    op.drop_index(op.f('ix_relationships_vault_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_to_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_rel_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_entity_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_facts_fact_type'), table_name='facts')
    op.drop_index(op.f('ix_facts_entity_id'), table_name='facts')
    op.drop_index('ix_facts_embedding', table_name='facts', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('facts')
    op.drop_index(op.f('ix_documents_vault_id'), table_name='documents')
    op.drop_index('ix_documents_embedding', table_name='documents', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('documents')
    op.drop_table('conflict_participants')
    op.drop_index(op.f('ix_character_states_sequence_order'), table_name='character_states')
    op.drop_index(op.f('ix_character_states_character_id'), table_name='character_states')
    op.drop_table('character_states')
    op.drop_index(op.f('ix_character_arcs_vault_id'), table_name='character_arcs')
    op.drop_index(op.f('ix_character_arcs_character_id'), table_name='character_arcs')
    op.drop_table('character_arcs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_themes_vault_id'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_sprints_vault_id'), table_name='sprints')
    op.drop_table('sprints')
    op.drop_table('sources')
    op.drop_index(op.f('ix_interactions_vault_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_event_type'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_events_vault_id'), table_name='events')
    op.drop_index(op.f('ix_events_sequence_order'), table_name='events')
    op.drop_index('ix_events_embedding', table_name='events', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('events')
    op.drop_index(op.f('ix_entities_vault_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_status'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index('ix_entities_embedding', table_name='entities', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('entities')
    op.drop_index(op.f('ix_conversations_vault_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_conflicts_vault_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_status'), table_name='conflicts')
    op.drop_index('ix_conflicts_embedding', table_name='conflicts', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_conflicts_conflict_type'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_chapters_vault_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_chapter_number'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_anchors_vault_id'), table_name='anchors')
    op.drop_index(op.f('ix_anchors_status'), table_name='anchors')
    op.drop_table('anchors')
    # ### end Alembic commands ###
