"""add hybrid architecture foundation (User, Vault, enums, vault_id isolation)

Revision ID: 67a879aff557
Revises: c3d4e5f6g7h8
Create Date: 2025-11-24 22:25:38.511675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67a879aff557'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create Users Table (New)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'MINI', 'PRO', 'BYOK', name='subscriptiontier'), nullable=False),
    sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # 2. Create Vaults Table (New)
    op.create_table('vaults',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('connection_type', sa.Enum('LOCAL_OBSIDIAN', 'CLOUD_HOSTED', name='connectiontype'), nullable=False),
    sa.Column('local_system_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('scene_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaults_owner_id'), 'vaults', ['owner_id'], unique=False)

    # 3. Add Columns to Entities (Existing Table)
    # Create enum type if it doesn't exist
    entity_status_enum = sa.Enum('ALIVE', 'DEAD', 'MISSING', 'UNKNOWN', 'UNDEAD', 'DORMANT', 'ASCENDED', 'IMPRISONED', 'EXILED', name='entitystatus')
    entity_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('entities', sa.Column('status', entity_status_enum, nullable=False, server_default='ALIVE'))
    op.add_column('entities', sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entities', sa.Column('species', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('entities', sa.Column('birth_date', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entities', sa.Column('death_date', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    op.create_index(op.f('ix_entities_status'), 'entities', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove columns from entities
    op.drop_index(op.f('ix_entities_status'), table_name='entities')
    op.drop_column('entities', 'death_date')
    op.drop_column('entities', 'birth_date')
    op.drop_column('entities', 'species')
    op.drop_column('entities', 'aliases')
    op.drop_column('entities', 'status')
    
    # Drop Vaults
    op.drop_index(op.f('ix_vaults_owner_id'), table_name='vaults')
    op.drop_table('vaults')
    
    # Drop Users
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    
    # ### end Alembic commands ###
