"""add_prerequisites_tracking_to_anchors

Revision ID: edabc2e83026
Revises: 125ebba5f7c3
Create Date: 2025-11-26 02:19:39.897179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'edabc2e83026'
down_revision: Union[str, Sequence[str], None] = '125ebba5f7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add anchor prerequisite tracking fields
    op.add_column('anchors', sa.Column('prerequisites_met', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('anchors', sa.Column('prerequisites_total', sa.Integer(), nullable=False, server_default='0'))

    # Create enum types for scene fields if they don't exist
    from sqlalchemy.dialects import postgresql
    scene_outcome_type = postgresql.ENUM('ACHIEVED', 'FAILED', 'SUBVERTED', 'MODIFIED', 'ABANDONED', name='sceneoutcometype', create_type=False)
    dramatic_function_type = postgresql.ENUM('EXPOSITION', 'INCITING_INCIDENT', 'RISING_ACTION', 'MIDPOINT', 'CRISIS', 'CLIMAX', 'FALLING_ACTION', 'RESOLUTION', 'DENOUEMENT', name='dramaticfunction', create_type=False)

    # Check if enums exist, create if not
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sceneoutcometype')"))
    if not result.scalar():
        scene_outcome_type.create(connection, checkfirst=True)

    result = connection.execute(sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dramaticfunction')"))
    if not result.scalar():
        dramatic_function_type.create(connection, checkfirst=True)

    # Drop HNSW indexes (will be recreated with updated settings)
    op.drop_index(op.f('conflicts_embedding_hnsw_idx'), table_name='conflicts', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('documents_embedding_hnsw_idx'), table_name='documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('entities_embedding_hnsw_idx'), table_name='entities', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('events_embedding_hnsw_idx'), table_name='events', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('facts_embedding_hnsw_idx'), table_name='facts', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('scenes_embedding_hnsw_idx'), table_name='scenes', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')

    # Add scene goal tracking fields
    op.add_column('scenes', sa.Column('scene_goal', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('scenes', sa.Column('scene_outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('scenes', sa.Column('outcome_type', scene_outcome_type, nullable=True))
    op.add_column('scenes', sa.Column('dramatic_function', dramatic_function_type, nullable=True))
    op.add_column('scenes', sa.Column('character_goal_met', sa.Boolean(), nullable=True))
    op.add_column('scenes', sa.Column('story_goal_progression', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('scenes', sa.Column('consequence', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('scenes', sa.Column('flags_for_later', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('scenes_embedding_hnsw_idx'), 'scenes', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('scenes', 'flags_for_later')
    op.drop_column('scenes', 'consequence')
    op.drop_column('scenes', 'story_goal_progression')
    op.drop_column('scenes', 'character_goal_met')
    op.drop_column('scenes', 'dramatic_function')
    op.drop_column('scenes', 'outcome_type')
    op.drop_column('scenes', 'scene_outcome')
    op.drop_column('scenes', 'scene_goal')
    op.create_index(op.f('facts_embedding_hnsw_idx'), 'facts', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('events_embedding_hnsw_idx'), 'events', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('entities_embedding_hnsw_idx'), 'entities', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('documents_embedding_hnsw_idx'), 'documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('conflicts_embedding_hnsw_idx'), 'conflicts', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('anchors', 'prerequisites_total')
    op.drop_column('anchors', 'prerequisites_met')
    # ### end Alembic commands ###
